---
- name: Starting Redis
  hosts: all
  task:
    - name: Set local redis instance to be a replica of melee.island on port 6377
      community.general.redis:
        command: replica
        master_host: { { master_host } }
        master_port: 6377

    - name: Deactivate replica mode
      community.general.redis:
        command: replica
        replica_mode: master

    - name: Flush all the redis db
      community.general.redis:
        command: flush
        flush_mode: all

    - name: Flush only one db in a redis instance
      community.general.redis:
        command: flush
        db: 1
        flush_mode: db

    - name: Configure local redis to have 10000 max clients
      community.general.redis:
        command: config
        name: maxclients
        value: 10000

    - name: Configure local redis maxmemory to 4GB
      community.general.redis:
        command: config
        name: maxmemory
        value: 4GB

    - name: Configure local redis to have lua time limit of 100 ms
      community.general.redis:
        command: config
        name: lua-time-limit
        value: 100
    - name: Ensure Redis is present
      apt: pkg=redis-server state=latest
      sudo: true

    - name: Ensure Redis is started
      service: name=redis-server state=started enabled=yes
      sudo: true

    - name: Ensure Redis Configuration
      template: src=redis.conf.j2 dest=/etc/redis/redis.conf owner=root group=root mode=0644
      sudo: true
      notify: Redis Restart

  handlers:
    - name: Redis Restart
      service: name=redis-server state=restarted enabled=yes
      sudo: true
