---
- hosts: all
  vars:
    dynatrace_api_url: "{{ dynatrace_api_url }}"
    dynatrace_token: "{{ token }}"
    state: "{{ state }}"
  tasks:
    - name: "update problem with comment before auto-remediation"
      when: state == "OPEN"
      uri:
        url: https://{{ dynatrace_api_url }}/api/v2/problems/{{ pid }}/comments?Api-Token={{ dynatrace_token }}
        method: POST
        body:
          comment: "Problem notification received by Ansible Tower.  Attempting to perform auto-remediation."
          message: "Problem notification received by Ansible Tower.  Attempting to perform auto-remediation."
          user: "Job {{ tower_job_id }}"
          context: Ansible Tower
        body_format: json
        status_code: 201
    - name: enable tomcat services and start
      become: yes
      systemd:
          name: tomcat
          state: started 
          enabled: yes
    - name: "update problem with comment after remediation"
      when: state == "OPEN" 
      uri:
        url: https://{{ dynatrace_api_url }}/api/v2/problems/{{ pid }}/comments?Api-Token={{ dynatrace_token }}
        method: POST
        body:
          comment: "Successfully triggered auto-remediation."
          message: "Successfully triggered auto-remediation."
          user: "Job {{ tower_job_id }}"
          context: Ansible Tower
        body_format: json
        status_code: 201
